rap:
  username: 78276
  password: sschnitzer1
price_list:
  extra_discount: 5
  min_number_of_results_to_display: 50
start_xvsb: true
ranges:
  size:
    start: 0.3
    end: 1.5
  cut: ["Excellent"]
  polish: ["Excellent"]
  sym: ["Excellent"]
  clarity: ["IF", "VVS1", "VVS2", "VS1", "VS2", "SI1", "SI2", "I1"]
  color:
    start: "D"
    end: "M"
  flour: ["None", "Faint", "Medium", "Strong"]
