require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AdjustmentsController do

  # This should return the minimal set of attributes required to create a valid
  # Adjustment. As you add validations to Adjustment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "weight" => "9.99" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AdjustmentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all adjustments as @adjustments" do
      adjustment = Adjustment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:adjustments).should eq([adjustment])
    end
  end

  describe "GET show" do
    it "assigns the requested adjustment as @adjustment" do
      adjustment = Adjustment.create! valid_attributes
      get :show, {:id => adjustment.to_param}, valid_session
      assigns(:adjustment).should eq(adjustment)
    end
  end

  describe "GET new" do
    it "assigns a new adjustment as @adjustment" do
      get :new, {}, valid_session
      assigns(:adjustment).should be_a_new(Adjustment)
    end
  end

  describe "GET edit" do
    it "assigns the requested adjustment as @adjustment" do
      adjustment = Adjustment.create! valid_attributes
      get :edit, {:id => adjustment.to_param}, valid_session
      assigns(:adjustment).should eq(adjustment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Adjustment" do
        expect {
          post :create, {:adjustment => valid_attributes}, valid_session
        }.to change(Adjustment, :count).by(1)
      end

      it "assigns a newly created adjustment as @adjustment" do
        post :create, {:adjustment => valid_attributes}, valid_session
        assigns(:adjustment).should be_a(Adjustment)
        assigns(:adjustment).should be_persisted
      end

      it "redirects to the created adjustment" do
        post :create, {:adjustment => valid_attributes}, valid_session
        response.should redirect_to(Adjustment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved adjustment as @adjustment" do
        # Trigger the behavior that occurs when invalid params are submitted
        Adjustment.any_instance.stub(:save).and_return(false)
        post :create, {:adjustment => { "weight" => "invalid value" }}, valid_session
        assigns(:adjustment).should be_a_new(Adjustment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Adjustment.any_instance.stub(:save).and_return(false)
        post :create, {:adjustment => { "weight" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested adjustment" do
        adjustment = Adjustment.create! valid_attributes
        # Assuming there are no other adjustments in the database, this
        # specifies that the Adjustment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Adjustment.any_instance.should_receive(:update).with({ "weight" => "9.99" })
        put :update, {:id => adjustment.to_param, :adjustment => { "weight" => "9.99" }}, valid_session
      end

      it "assigns the requested adjustment as @adjustment" do
        adjustment = Adjustment.create! valid_attributes
        put :update, {:id => adjustment.to_param, :adjustment => valid_attributes}, valid_session
        assigns(:adjustment).should eq(adjustment)
      end

      it "redirects to the adjustment" do
        adjustment = Adjustment.create! valid_attributes
        put :update, {:id => adjustment.to_param, :adjustment => valid_attributes}, valid_session
        response.should redirect_to(adjustment)
      end
    end

    describe "with invalid params" do
      it "assigns the adjustment as @adjustment" do
        adjustment = Adjustment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Adjustment.any_instance.stub(:save).and_return(false)
        put :update, {:id => adjustment.to_param, :adjustment => { "weight" => "invalid value" }}, valid_session
        assigns(:adjustment).should eq(adjustment)
      end

      it "re-renders the 'edit' template" do
        adjustment = Adjustment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Adjustment.any_instance.stub(:save).and_return(false)
        put :update, {:id => adjustment.to_param, :adjustment => { "weight" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested adjustment" do
      adjustment = Adjustment.create! valid_attributes
      expect {
        delete :destroy, {:id => adjustment.to_param}, valid_session
      }.to change(Adjustment, :count).by(-1)
    end

    it "redirects to the adjustments list" do
      adjustment = Adjustment.create! valid_attributes
      delete :destroy, {:id => adjustment.to_param}, valid_session
      response.should redirect_to(adjustments_url)
    end
  end

end
